export const inputs = {
	anoReferencia: 2023,
	investimentoAcumulado: 0,
	investimentoMensal: [
		{ codigo: "janeiroValor", valor: "0" },
		{ codigo: "fevereiroValor", valor: "0" },
		{ codigo: "marcoValor", valor: "0" },
		{ codigo: "abrilValor", valor: "0" },
		{ codigo: "maioValor", valor: "0" },
		{ codigo: "junhoValor", valor: "0" },
		{ codigo: "julhoValor", valor: "0" },
		{ codigo: "agostoValor", valor: "0" },
		{ codigo: "setembroValor", valor: "0" },
		{ codigo: "outubroValor", valor: "0" },
		{ codigo: "novembroValor", valor: "0" },
		{ codigo: "dezembroValor", valor: "0" },
	],
	empregoHomem: [
		{ codigo: "janeiroValor", valor: "1" },
		{ codigo: "fevereiroValor", valor: "2" },
		{ codigo: "marcoValor", valor: "3" },
		{ codigo: "abrilValor", valor: "4" },
		{ codigo: "maioValor", valor: "5" },
		{ codigo: "junhoValor", valor: "6" },
		{ codigo: "julhoValor", valor: "7" },
		{ codigo: "agostoValor", valor: "8" },
		{ codigo: "setembroValor", valor: "9" },
		{ codigo: "outubroValor", valor: "10" },
		{ codigo: "novembroValor", valor: "11" },
		{ codigo: "dezembroValor", valor: "12" },
	],
	empregoMulher: [
		{ codigo: "janeiroValor", valor: "1" },
		{ codigo: "fevereiroValor", valor: "2" },
		{ codigo: "marcoValor", valor: "3" },
		{ codigo: "abrilValor", valor: "4" },
		{ codigo: "maioValor", valor: "5" },
		{ codigo: "junhoValor", valor: "6" },
		{ codigo: "julhoValor", valor: "7" },
		{ codigo: "agostoValor", valor: "8" },
		{ codigo: "setembroValor", valor: "9" },
		{ codigo: "outubroValor", valor: "10" },
		{ codigo: "novembroValor", valor: "11" },
		{ codigo: "dezembroValor", valor: "12" },
	],
};
