export const inputs = {
	anoReferencia: 2023,
	investimentoAcumulado: 0,
	investimentoMensal: [
		{ codigo: "janeiroValor", valor: "" },
		{ codigo: "fevereiroValor", valor: "" },
		{ codigo: "marcoValor", valor: "" },
		{ codigo: "abrilValor", valor: "" },
		{ codigo: "maioValor", valor: "" },
		{ codigo: "junhoValor", valor: "" },
		{ codigo: "julhoValor", valor: "" },
		{ codigo: "agostoValor", valor: "" },
		{ codigo: "setembroValor", valor: "" },
		{ codigo: "outubroValor", valor: "" },
		{ codigo: "novembroValor", valor: "" },
		{ codigo: "dezembroValor", valor: "" },
	],
	empregoHomem: [
		{ codigo: "janeiroValor", valor: "" },
		{ codigo: "fevereiroValor", valor: "" },
		{ codigo: "marcoValor", valor: "" },
		{ codigo: "abrilValor", valor: "" },
		{ codigo: "maioValor", valor: "" },
		{ codigo: "junhoValor", valor: "" },
		{ codigo: "julhoValor", valor: "" },
		{ codigo: "agostoValor", valor: "" },
		{ codigo: "setembroValor", valor: "" },
		{ codigo: "outubroValor", valor: "" },
		{ codigo: "novembroValor", valor: "" },
		{ codigo: "dezembroValor", valor: "" },
	],
	empregoMulher: [
		{ codigo: "janeiroValor", valor: "" },
		{ codigo: "fevereiroValor", valor: "" },
		{ codigo: "marcoValor", valor: "" },
		{ codigo: "abrilValor", valor: "" },
		{ codigo: "maioValor", valor: "" },
		{ codigo: "junhoValor", valor: "" },
		{ codigo: "julhoValor", valor: "" },
		{ codigo: "agostoValor", valor: "" },
		{ codigo: "setembroValor", valor: "" },
		{ codigo: "outubroValor", valor: "" },
		{ codigo: "novembroValor", valor: "" },
		{ codigo: "dezembroValor", valor: "" },
	],
};
