export const inputs = {
	anoReferencia: 2023,
	investimentoAcumulado: 0,
	investimentoMensal: {
		janeiroValor: 0,
		fevereiroValor: 0,
		marcoValor: 0,
		abrilValor: 0,
		maioValor: 0,
		junhoValor: 0,
		julhoValor: 0,
		agostoValor: 0,
		setembroValor: 0,
		outubroValor: 0,
		novembroValor: 0,
		dezembroValor: 0,
	},
	empregoHomem: {
		janeiroValor: "1",
		fevereiroValor: "2",
		marcoValor: "3",
		abrilValor: "4",
		maioValor: "5",
		junhoValor: "6",
		julhoValor: "7",
		agostoValor: "8",
		setembroValor: "9",
		outubroValor: "10",
		novembroValor: "11",
		dezembroValor: "12",
	},
	empregoMulher: {
		janeiroValor: "1",
		fevereiroValor: "2",
		marcoValor: "3",
		abrilValor: "4",
		maioValor: "5",
		junhoValor: "6",
		julhoValor: "7",
		agostoValor: "8",
		setembroValor: "9",
		outubroValor: "10",
		novembroValor: "11",
		dezembroValor: "12",
	},
};
