export const inputs = {
	beneficiario: {
		dataAtualizacao: "",
		dataCadastro: "",
		id: 0,
	},
	incentivoFiscal: {
		id: 0,
		sigla: "",
		descricao: "",
		fundos: [],
	},
	valoresFundo: [],
	submodulo: 0,
	codigoRcr: "",
	recolhimentoFundos: [
		{
			abrilValor: null,
			agostoValor: null,
			anoReferencia: null,
			dezembroValor: null,
			fevereiroValor: null,
			fundoIncentivo: {
				dataAtualizacao: "",
				dataCadastro: "",
				id: null,
			},
			janeiroValor: null,
			julhoValor: null,
			junhoValor: null,
			maioValor: null,
			marcoValor: null,
			novembroValor: null,
			outubroValor: null,
			setembroValor: null,
			submodulo: {
				dataAtualizacao: "",
				dataCadastro: "",
				id: null,
			},
		},
	],
	vendaAnualInterestadual: 0,
	vendaAnualInterna: 0,
};
