export const inputs = {
	beneficiario: {
		dataAtualizacao: "",
		dataCadastro: "",
		id: 0,
	},
	incentivoFiscal: {
		id: 0,
		sigla: "",
		descricao: "",
		fundos: [],
	},
	valoresFundo: [],
	submodulo: 0,
	codigoRcr: "",
	recolhimentoFundos: [
		{
			abrilValor: 0,
			agostoValor: 0,
			anoReferencia: 0,
			dezembroValor: 0,
			fevereiroValor: 0,
			fundoIncentivo: {
				dataAtualizacao: "",
				dataCadastro: "",
				id: 0,
			},
			janeiroValor: 0,
			julhoValor: 0,
			junhoValor: 0,
			maioValor: 0,
			marcoValor: 0,
			novembroValor: 0,
			outubroValor: 0,
			setembroValor: 0,
			submodulo: {
				dataAtualizacao: "",
				dataCadastro: "",
				id: 0,
			},
		},
	],
	vendaAnualInterestadual: 0,
	vendaAnualInterna: 0,
};
