export const inputs = {
	nomeOuRazaoSocial: "",
	cpfOuCnpj: "",
	email: "",
	telefoneEmpresa: null,
	telefoneContabilidade: null,
	nomeFantasia: "",
	inscricaoEstadual: null,
	nomeAdministrador: "",
	telefoneAdministrador: null,
	municipio: null,
	porte: "",
	ramoAtividade: "",
	descricao: "",
	cnaes: [],
	telefones: [],
	status: [],
	dadosEconomicos: {
		anoReferencia: null,
		investimentoAcumulado: null,
		investimentoMensal: {
			janeiroValor: null,
			fevereiroValor: null,
			marcoValor: null,
			abrilValor: null,
			maioValor: null,
			junhoValor: null,
			julhoValor: null,
			agostoValor: null,
			setembroValor: null,
			outubroValor: null,
			novembroValor: null,
			dezembroValor: null,
		},
		empregoHomem: {
			janeiroValor: null,
			fevereiroValor: null,
			marcoValor: null,
			abrilValor: null,
			maioValor: null,
			junhoValor: null,
			julhoValor: null,
			agostoValor: null,
			setembroValor: null,
			outubroValor: null,
			novembroValor: null,
			dezembroValor: null,
		},
		empregoMulher: {
			janeiroValor: null,
			fevereiroValor: null,
			marcoValor: null,
			abrilValor: null,
			maioValor: null,
			junhoValor: null,
			julhoValor: null,
			agostoValor: null,
			setembroValor: null,
			outubroValor: null,
			novembroValor: null,
			dezembroValor: null,
		},
	},
};
