export const inputs = {
	anoReferencia: (new Date().getFullYear() - 1),
	investimentoAcumulado: 0,
	investimentoMensal: [
		{ codigo: "janeiroValor", valor: "" },
		{ codigo: "fevereiroValor", valor: "" },
		{ codigo: "marcoValor", valor: "" },
		{ codigo: "abrilValor", valor: "" },
		{ codigo: "maioValor", valor: "" },
		{ codigo: "junhoValor", valor: "" },
		{ codigo: "julhoValor", valor: "" },
		{ codigo: "agostoValor", valor: "" },
		{ codigo: "setembroValor", valor: "" },
		{ codigo: "outubroValor", valor: "" },
		{ codigo: "novembroValor", valor: "" },
		{ codigo: "dezembroValor", valor: "" },
	],
	empregoHomem: [
		{ codigo: "janeiroValor", valor: "" },
		{ codigo: "fevereiroValor", valor: "" },
		{ codigo: "marcoValor", valor: "" },
		{ codigo: "abrilValor", valor: "" },
		{ codigo: "maioValor", valor: "" },
		{ codigo: "junhoValor", valor: "" },
		{ codigo: "julhoValor", valor: "" },
		{ codigo: "agostoValor", valor: "" },
		{ codigo: "setembroValor", valor: "" },
		{ codigo: "outubroValor", valor: "" },
		{ codigo: "novembroValor", valor: "" },
		{ codigo: "dezembroValor", valor: "" },
	],
	empregoMulher: [
		{ codigo: "janeiroValor", valor: "" },
		{ codigo: "fevereiroValor", valor: "" },
		{ codigo: "marcoValor", valor: "" },
		{ codigo: "abrilValor", valor: "" },
		{ codigo: "maioValor", valor: "" },
		{ codigo: "junhoValor", valor: "" },
		{ codigo: "julhoValor", valor: "" },
		{ codigo: "agostoValor", valor: "" },
		{ codigo: "setembroValor", valor: "" },
		{ codigo: "outubroValor", valor: "" },
		{ codigo: "novembroValor", valor: "" },
		{ codigo: "dezembroValor", valor: "" },
	],
	infoVendas: [
		{
			ncm: null,
			produtoIncentivado: "",
			quantidadeInterestadual: "",
			quantidadeInterna: "",
			unidadeMedida: "",
		},
		{
			ncm: null,
			produtoIncentivado: "",
			quantidadeInterestadual: "",
			quantidadeInterna: "",
			unidadeMedida: "",
		},
	],

	beneficiario: {
		dataAtualizacao: "",
		dataCadastro: "",
		id: 0,
	},
	incentivoFiscal: {
		id: 0,
		sigla: "",
		descricao: "",
		fundos: [],
	},
	valoresFundo: [],
	submodulo: null,
	codigoRcr: "",
	recolhimentoFundos: [
		{
			abrilValor: null,
			agostoValor: null,
			anoReferencia: (new Date().getFullYear() - 1),
			dezembroValor: null,
			fevereiroValor: null,
			fundoIncentivo: {
				dataAtualizacao: "",
				dataCadastro: "",
				id: null,
			},
			janeiroValor: null,
			julhoValor: null,
			junhoValor: null,
			maioValor: null,
			marcoValor: null,
			novembroValor: null,
			outubroValor: null,
			setembroValor: null,
			submodulo: {
				dataAtualizacao: "",
				dataCadastro: "",
				id: null,
			},
		},
	],
	vendaAnualInterestadual: null,
	vendaAnualInterna: null,
	fundos: [],
};
