export const unidadesDeMedida = [
	{ key: 1, value: "Quilograma (kg)" },
	{ key: 2, value: "Grama (g)" },
	{ key: 3, value: "Miligrama (mg)" },
	{ key: 4, value: "Tonelada (t)" },
	{ key: 5, value: "Libra (lb)" },
	{ key: 6, value: "Onça (oz)" },
	{ key: 7, value: "Litro (L)" },
	{ key: 8, value: "Mililitro (ml)" },
	{ key: 9, value: "Galão (gal)" },
	{ key: 10, value: "Quart (qt)" },
	{ key: 11, value: "Pint (pt)" },
	{ key: 12, value: "Onça fluida (floz)" },
	{ key: 13, value: "Metro (m)" },
	{ key: 14, value: "Centímetro (cm)" },
	{ key: 15, value: "Milímetro (mm)" },
	{ key: 16, value: "Quilômetro (km)" },
	{ key: 17, value: "Jarda (yd)" },
	{ key: 18, value: "Pé (ft)" },
	{ key: 19, value: "Polegada (in)" },
	{ key: 20, value: "Metro quadrado (m²)" },
	{ key: 21, value: "Centímetro quadrado (cm²)" },
	{ key: 22, value: "Milímetro quadrado (mm²)" },
	{ key: 23, value: "Hectare (ha)" },
	{ key: 24, value: "Acre (acre)" },
	{ key: 25, value: "Metro cúbico (m³)" },
	{ key: 26, value: "Centímetro cúbico (cm³)" },
	{ key: 27, value: "Milímetro cúbico (mm³)" },
];
