export const unidadesDeMedida = [
	{ key: "kg", value: "Quilograma (kg)" },
	{ key: "g", value: "Grama (g)" },
	{ key: "mg", value: "Miligrama (mg)" },
	{ key: "t", value: "Tonelada (t)" },
	{ key: "lb", value: "Libra (lb)" },
	{ key: "oz", value: "Onça (oz)" },
	{ key: "L", value: "Litro (L)" },
	{ key: "ml", value: "Mililitro (ml)" },
	{ key: "gal", value: "Galão (gal)" },
	{ key: "qt", value: "Quart (qt)" },
	{ key: "pt", value: "Pint (pt)" },
	{ key: "floz", value: "Onça fluida (floz)" },
	{ key: "m", value: "Metro (m)" },
	{ key: "cm", value: "Centímetro (cm)" },
	{ key: "mm", value: "Milímetro (mm)" },
	{ key: "km", value: "Quilômetro (km)" },
	{ key: "yd", value: "Jarda (yd)" },
	{ key: "ft", value: "Pé (ft)" },
	{ key: "in", value: "Polegada (in)" },
	{ key: "m²", value: "Metro quadrado (m²)" },
	{ key: "cm²", value: "Centímetro quadrado (cm²)" },
	{ key: "mm²", value: "Milímetro quadrado (mm²)" },
	{ key: "ha", value: "Hectare (ha)" },
	{ key: "acre", value: "Acre (acre)" },
	{ key: "m³", value: "Metro cúbico (m³)" },
	{ key: "cm³", value: "Centímetro cúbico (cm³)" },
	{ key: "mm³", value: "Milímetro cúbico (mm³)" },
];
